### ISSUE TITLE
Type declarations do not accurately represent the package

### ISSUE THREAD

**Issue by tpluscode** [Download/anylogger#20]
Hello. I noticed that with latest typescript, using `moduleResolution: "Node16"`, the package stops working because it is not an ESM package (no `type: "module"`) but the type declaration represents a module `export default anylogger`

I might propose to simply change that to `export = anylogger` but given that the source itself is written as a module and even bundled in the package, I might propose actually going for a "proper" dual package.

**Comment by Download** [comment]
I am willing to merge a PR but I wonder whether you thought this change through. I would hate to break existing users. What is the effect of adding the namespace? It looks to me like all old imports will break?

**Comment by Download** [comment]
Have you tried adding `esModuleInterop: true` to *tsconfig.json*?

**Comment by tpluscode** [comment]
It appears to be a bit more nuanced. I wanted to rely on declaration merging but that does not work in this case. At least I failed to come up with the right structure. Also, I found that the new `Node16` module resolution changes the behavior...

I would probably consider a v2 which drops the build step and only publish the source ESM version. Modules have become so popular that bundling multiple build flavours

**Comment by Download** [comment]
@tpluscode 
Yeah I know, it is very complicated stuff... 😅

I am actually considering a v2 version written in Typescript... Not sure if I am able to get it as small as I like with Typescript. Would you be interested in contributing to such an idea?

**Comment by tpluscode** [comment]
I'd be glad to help where I can. Anylogger is not super complicated. A TypeScript conversion is definitely an option. Alternatively, you could keep JS but use `tsc` to type checking and to generate type declarations. I've been doing that to existing JS projects and it's less work and sometimes requires less modifications in code.

Unless you have some great plans for anylogger, I'd simply change to modules and add necessary JSDoc annotations and type checking. WDYT?

**Comment by Download** [comment]
@tpluscode Have a look at the current work in progress in the 1.1 branch

**Comment by tpluscode** [comment]
Thanks. Will check it this week

**Comment by tpluscode** [comment]
Hey. I just installed 1.1 beta. From I could quickly tell, the type resolution issues are gone 👌

**Comment by tpluscode** [comment]
I do have issues though. 

First, `anylogger-debug` allows `1.0.x` of `anylogger` which can results in duplicate resolution. See my output `npm ls`

```
talos@ /Users/tplus/projects/github/hydrofoil/talos
├─┬ @hydrofoil/talos-core@0.1.0 -> ./packages/core
│ └── anylogger@1.1.0-beta.5
└─┬ @hydrofoil/talos@0.6.4 -> ./packages/cli
  ├─┬ @tpluscode/sparql-builder@2.0.2
  │ └── anylogger@1.0.11
  ├─┬ anylogger-debug@1.1.0-beta.5
  │ └── anylogger@1.0.11 deduped                 <- I expected beta here
  └── anylogger@1.1.0-beta.5
```

Second, you should remove `.ts` files from packages. `tsc` will try to transpile them and potentially choke on some missing types. In my case, I think this is related to the duplicate resolution

```
✗ tsc --noEmit
node_modules/anylogger-debug/anylogger-debug.ts:2:8 - error TS2614: Module '"anylogger"' has no exported member 'LogLevel'. Did you mean to use 'import LogLevel from "anylogger"' instead?

2   type LogLevel,
         ~~~~~~~~

node_modules/anylogger-debug/anylogger-debug.ts:4:8 - error TS2614: Module '"anylogger"' has no exported member 'Adapter'. Did you mean to use 'import Adapter from "anylogger"' instead?

4   type Adapter,
         ~~~~~~~

node_modules/anylogger-debug/anylogger-debug.ts:8:27 - error TS7006: Parameter 'anylogger' implicitly has an 'any' type.

8 const adapter: Adapter = (anylogger, debug) => {
                            ~~~~~~~~~

node_modules/anylogger-debug/anylogger-debug.ts:8:38 - error TS7006: Parameter 'debug' implicitly has an 'any' type.

8 const adapter: Adapter = (anylogger, debug) => {
                                       ~~~~~

node_modules/anylogger-debug/anylogger-debug.ts:12:28 - error TS7006: Parameter 'logger' implicitly has an 'any' type.

12   anylogger.ext = function(logger) {
                              ~~~~~~

node_modules/anylogger-debug/anylogger-debug.ts:15:7 - error TS7053: Element implicitly has an 'any' type because expression of type 'LogLevel' can't be used to index type 'BaseLogger<BaseLevels> & {}'.

15       (logger as Logger)[level as LogLevel] = method
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 6 errors in the same file, starting at: node_modules/anylogger-debug/anylogger-debug.ts:2
```

**Comment by tpluscode** [comment]
> In my case, I think this is related to the duplicate resolution

Yea, if I ensure that all `anylogger*` packages are installed in the beta version I get less errors but still `Could not find a declaration file for module 'debug'`, which should not be the case.

Ah, and yes, the duplicate resolution means that the logging does not work at all. Probably gets hooked up with the wrong instance of `anylogger`

**Comment by Download** [comment]
Mmm yes it still needs some work. That I am a bit of a n00b in TS is not helping. 

The `anylogger-debug` package is pretty small. Maybe you can fork it and try if you can improve it? I did run some tests with it and did not get the same issues as you are experiencing

**Comment by tpluscode** [comment]
Happy to help :)

For the `-debug` package, the problem is reproducible when you install another package which depends on 1.0.

**Comment by tpluscode** [comment]
On a related note, have you considered a monorepo? It makes matters easier when you have `anylogger` and numerous `anylogger-X`. In fact, I may be also interested in contributing `anylogger-winston` and potentially `anylogger-pico`
